version: '3'
services:
    pwn:
        container_name: pwn_test
        image: skysider/pwndocker
        security_opt:
            - seccomp:unconfined
        cap_add:
            - SYS_PTRACE
        ports:
            - "23946:23946"
